### ISSUE TITLE
How do you doing?

### ISSUE THREAD

**Issue by anntoque** [amamori/github-tutorial#1]
6d2f4e4
# これはアイアンマンです
## これはアイアンマンです
![51cjlfdyw l](https://cloud.githubusercontent.com/assets/12080404/11458260/e7858198-96ff-11e5-87b8-a5e5cc15b00e.jpg)

**Comment by amamori** [comment]
Pull Requestやってみたってこと？

**Comment by anntoque** [comment]
###### いやこれはちがう

**Comment by amamori** [comment]
これって何したら行ける感じなん？

**Comment by anntoque** [comment]
- [x] どういう意味？

**Comment by amamori** [comment]
これはどうやったらできるのかなーって思ってさ．
あとは，コマンドライン上から送ってるのかなーっていうのも気になってた

**Comment by anntoque** [comment]
これってなに笑
コマンドラインじゃないよ笑
普通にこういう感じで打ってるよ。

<img width="1280" alt="2015-11-30 2 20 46" src="https://cloud.githubusercontent.com/assets/12080404/11458725/fd7fe692-9708-11e5-9c72-0bb01718b4f3.png">

**Comment by amamori** [comment]
あ．そうなん？
めっちゃ勉強してるんだと思って「こいつやるじゃん」って思ってたw

**Comment by anntoque** [comment]
Issueはただの掲示板みたいなもんだからな

**Comment by amamori** [comment]
開発を行う上でこの機能はいいよな．
メモとか，進捗の問題点とか書けるし．
連絡機能が別ってなるといろいろ不便なこともあるし

**Comment by anntoque** [comment]
:+1:
